import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import type { JsonObject } from "./contractLib.js";
import { writeJson } from "./generatorIo.js";
import { buildComponentInstructions, buildSlideSelectionInstruction } from "./aiInstructionOutput.js";
import { loadComponentsInstruction, type ComponentSource } from "./componentSources.js";
import { loadSlideSelectionSchema, loadSlidesInstructions } from "./presentationSources.js";
import { generatedAiComponentsDir, generatedAiDir, tsAiDir } from "./generatorPaths.js";

// Generates AI component instruction artifacts (per-component JSON, aggregate
// catalog JSON, and a TS export) from authored tag `ai` metadata + content
// contracts. Derived only from contracts/components/*, shared fragments, and content
// contracts; do not hand-edit the outputs.
export async function buildAiInstructionOutputs(
  sharedSchema: JsonObject,
  componentSources: ComponentSource[],
): Promise<void> {
  const instruction = await loadComponentsInstruction();
  const { perComponent, aggregate } = buildComponentInstructions(sharedSchema, componentSources, instruction);

  await mkdir(generatedAiComponentsDir, { recursive: true });
  for (const { componentType } of componentSources) {
    await writeJson(
      path.join(generatedAiComponentsDir, `${componentType}.instruction.json`),
      perComponent[componentType],
    );
  }
  await writeJson(path.join(generatedAiDir, "component-instructions.json"), aggregate);

  await mkdir(tsAiDir, { recursive: true });
  const tsSource = `// DO NOT EDIT - generated by scripts/generate-ts-contracts.ts

export const componentInstructions = ${JSON.stringify(aggregate, null, 2)} as const;

export type ComponentInstructions = typeof componentInstructions;
export type ComponentInstruction = ComponentInstructions["component_instructions"][keyof ComponentInstructions["component_instructions"]];
`;
  await writeFile(path.join(tsAiDir, "componentInstructions.ts"), tsSource);
}

// Generates the static slide-selection AI instruction artifact (JSON + TS mirror)
// from the authored description, slide tag ai metadata, and the authored
// slide-selection response schema. Reusable prompt metadata, not a
// template-specific slide catalog.
export async function buildSlideSelectionInstructionOutputs(slideSchema: JsonObject): Promise<void> {
  const slidesInstructions = await loadSlidesInstructions();
  const slideSelectionSchema = await loadSlideSelectionSchema();
  const artifact = buildSlideSelectionInstruction(slidesInstructions, slideSchema, slideSelectionSchema);

  await mkdir(generatedAiDir, { recursive: true });
  await writeJson(path.join(generatedAiDir, "slide-selection.instruction.json"), artifact);

  await mkdir(tsAiDir, { recursive: true });
  const tsSource = `// DO NOT EDIT - generated by scripts/generate-ts-contracts.ts

export const slideSelectionInstructions = ${JSON.stringify(artifact, null, 2)} as const;

export type SlideSelectionInstructions = typeof slideSelectionInstructions;
`;
  await writeFile(path.join(tsAiDir, "slideSelectionInstructions.ts"), tsSource);
}
