import { getRecord, type JsonObject } from "./contractLib.js";

// Emits the generated TS for the deck (presentation-level) tag schema. Mirrors
// slideTsOutput.ts but is intentionally minimal — deck tags are a small metadata
// set. Tag-name constants are DECK_-prefixed (e.g. DECK_TEMPLATE_ID_TAG) to
// disambiguate from the structural template.contract.json `template_id`.
export function buildDeckTagSchemaSource(schema: JsonObject): string {
  const tags = getRecord(schema, "tags");
  const allTags = Object.keys(tags);
  const schemaJson = JSON.stringify(
    { generated_from: "contracts/presentation/deck/tags.contract.json", ...schema },
    null,
    2,
  );

  const tagConstantLines = allTags
    .map((tag) => `export const ${tagToConstantName(tag)} = ${JSON.stringify(tag)};`)
    .join("\n");

  return `// DO NOT EDIT - generated by scripts/generate-ts-contracts.ts
// Source: contracts/presentation/deck/tags.contract.json

export const deckTagSchema = ${schemaJson} as const;

export type DeckTagSchema = typeof deckTagSchema;

export const deckTagKeys = ${JSON.stringify(allTags, null, 2)} as const;

${tagConstantLines}
`;
}

function tagToConstantName(tag: string): string {
  return `DECK_${tag.replace(/^efficio_/, "").toUpperCase()}_TAG`;
}
