import { readFile, writeFile } from "node:fs/promises";

// Shared read/write/format helpers used by the source loaders and output
// builders. Output formatting (trailing newline, 2-space JSON, the generated
// header) lives here so every artifact is byte-identical regardless of caller.

export async function readJson(filePath: string): Promise<unknown> {
  return JSON.parse(await readFile(filePath, "utf8")) as unknown;
}

export async function writeJson(filePath: string, value: unknown): Promise<void> {
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

export function buildConstSource(
  exportName: string,
  value: unknown,
  extraLines: string[] = [],
  headerLines: string[] = [],
): string {
  const header = [
    "// DO NOT EDIT - generated by packages/efficio-ppt-components/scripts/generate-ts-contracts.ts",
    ...headerLines,
  ].join("\n");
  const footer = extraLines.length > 0 ? `\n${extraLines.join("\n")}\n` : "";
  return `${header}\n\nexport const ${exportName} = ${JSON.stringify(value, null, 2)} as const;\n${footer}`;
}

export function toCamelCase(value: string): string {
  return value.replace(/_([a-z])/g, (_match, letter: string) => letter.toUpperCase());
}
