import { getRecord, type JsonObject } from "./contractLib.js";

export function buildSlideTagSchemaSource(schema: JsonObject): string {
  const tags = getRecord(schema, "tags");
  const allTags = Object.keys(tags);
  const schemaJson = JSON.stringify(
    { generated_from: "contracts/presentation/slide/tags.contract.json", ...schema },
    null,
    2,
  );

  const tagConstantLines = allTags
    .map((tag) => `export const ${tagToConstantName(tag)} = ${JSON.stringify(tag)};`)
    .join("\n");

  const enumLines = allTags
    .filter((tag) => Array.isArray(getRecord(tags, tag).enum))
    .map((tag) => {
      const constName = tagToEnumConstantName(tag);
      const typeName = tagToTypeName(tag);
      return `export const ${constName} = slideTagSchema.tags[${JSON.stringify(tag)}].enum;\nexport type ${typeName} = (typeof ${constName})[number];`;
    })
    .join("\n\n");

  const maxLengthLines = allTags
    .filter((tag) => typeof getRecord(tags, tag).max_length === "number")
    .map(
      (tag) =>
        `export const ${tagToMaxLengthConstantName(tag)} = slideTagSchema.tags[${JSON.stringify(tag)}].max_length;`,
    )
    .join("\n");

  return `// DO NOT EDIT - generated by packages/efficio-ppt-components/scripts/generate-ts-contracts.ts
// Source: contracts/presentation/slide/tags.contract.json

export const slideTagSchema = ${schemaJson} as const;

export type SlideTagSchema = typeof slideTagSchema;

export const slideTagKeys = ${JSON.stringify(allTags, null, 2)} as const;

${tagConstantLines}

${enumLines}

${maxLengthLines}
`;
}

function tagToConstantName(tag: string): string {
  return `${tag.replace(/^efficio_/, "").toUpperCase()}_TAG`;
}

function tagToEnumConstantName(tag: string): string {
  const base = tag.replace(/^efficio_/, "").toUpperCase();
  return base.endsWith("_POLICY") ? base.replace(/_POLICY$/, "_POLICIES") : `${base}S`;
}

function tagToTypeName(tag: string): string {
  return `Slide${tag
    .replace(/^efficio_slide_/, "")
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")}`;
}

function tagToMaxLengthConstantName(tag: string): string {
  return `${tag.replace(/^efficio_/, "").toUpperCase()}_MAX_LENGTH`;
}
